spring:
  main:
    banner-mode: "off"
#  datasource:
#    url: jdbc:postgresql://localhost:5432/Teste_Kotlin
#    username: postgres
#    password: postgres
#    platform: POSTGRESQL

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=1
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    concurrentconsumers: 1
    maxconcurrentconsumers: 1

server:
  port: 8888

mongodb:
  database: "test"
  host: "127.0.0.1"
  port: "27017"

messaging:
  host: "192.168.99.100"
  username: "guest"
  password: "guest"

security:
  user:
    name: admin
    password: 123456
    role: SYSTEM